version: '3.8'

services:
  server:
    build:
      context: rusty-backend
    ports:
      - "3117:3117"
    env_file: ./rusty-backend/config.env
    environment:
      CONFIG_DB__URL: <your-db-url>
    healthcheck:
      test: curl -f http://localhost:3117/health
      interval: 1s
      retries: 5
      start_period: 1s
      timeout: 2s
  webapp:
    build:
      context: app.metz
    ports:
      - "3000:3000"
    env_file: ./app.metz/.env
    depends_on:
      server:
        condition: service_healthy
