export enum Events {
	RESET = 'RESET',
	PLAY = 'PLAY',
	NEXT = 'NEXT',
	METZ_BLOCK_RENDERED = 'METZ_BLOCK_RENDERED',
	LAB_VISITED = 'LAB_VISITED',
	POST_OPENED = 'POST_OPENED',
	CONSOLE_OPENED = 'CONSOLE_OPENED',
	TIMELINE_ITEM_OPENED = 'TIMELINE_ITEM_OPENED',
	METZ_BLOCK_NODE_STATE_COMPLETED = 'METZ_BLOCK_NODE_STATE_COMPLETED',
}
